//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SCBiblioteca.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class DetalleCompra
    {
        public int IdDetalleCompra { get; set; }
        public int Cantidad { get; set; }
        public decimal Subtotal { get; set; }
        public int IdCompra { get; set; }
        public int IdLibro { get; set; }
    
        public virtual Compra Compra { get; set; }
        public virtual Libro Libro { get; set; }
    }
}
