//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SCBiblioteca.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Penalizacion
    {
        public int IdPenalizacion { get; set; }
        public decimal MontoPenalizacion { get; set; }
        public string MotivoPenalizacion { get; set; }
        public Nullable<int> IdDevolucion { get; set; }
    
        public virtual Devolucion Devolucion { get; set; }
    }
}
